apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: advisor-nest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: advisor-nest
  filterTags:
    pattern: '^v(?P<semver>[0-9]*\.[0-9]*\.[0-9]*)'
    extract: '$semver'
  policy:
    semver:
      range: '>=1.0.0'