apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda
  namespace: redpanda
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 5m
  chart:
    spec:
      chart: redpanda
      version: "5.7.*"
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: flux-system
      interval: 48h0m0s
  values:
    statefulset:
      replicas: 1
      initContainers:
        setDataDirOwnership:
          enabled: true
    tuning:
      tune_aio_events: false