apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-modernengineering
  namespace: modern-engineering
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghcr-modernengineering
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .token }}","auth":"{{ printf "%s:%s" .username .token | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: modernengineering-ghcr
        property: username
    - secretKey: token
      remoteRef:
        key: modernengineering-ghcr
        property: token
