apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: modernengineering
  namespace: flux-system
spec:
  image: ghcr.io/modernengineering/website
  interval: 5m
  secretRef:
    name: ghcr-modernengineering