apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: jellyfin
spec:
  type: ClusterIP
  ports:
    - port: 6767
      targetPort: 6767
      name: http
  selector:
    app: bazarr
    app.kubernetes.io/part-of: jellyfin
