apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  type: ClusterIP
  ports:
    - port: 8096
      targetPort: 8096
      name: http
  selector:
    app: jellyfin
    app.kubernetes.io/part-of: jellyfin
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-lb
  namespace: jellyfin
  labels:
    bgp.cilium.io/ip-pool: default
    bgp.cilium.io/advertise-service: default
  annotations:
    io.cilium/lb-ipam-ips: "172.20.10.193"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 8096
    targetPort: 8096
    name: jellyfin
  selector:
    app: jellyfin
    app.kubernetes.io/part-of: jellyfin