apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: jellyfin
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      name: webui
    - port: 6881
      targetPort: 6881
      protocol: TCP
      name: tcp-port
    - port: 6881
      targetPort: 6881
      protocol: UDP
      name: udp-port
  selector:
    app: qbittorrent
    app.kubernetes.io/part-of: jellyfin
