apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - namespace.yaml
  - configmap.yaml
  - configmap-postgres.yaml
  - externalsecret.yaml
  - deployments
  - services
  - httproute.yaml
  - httproutes-admin.yaml
  - pv-nfs.yaml
  - pvc.yaml