apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - deployments
  - namespace.yaml
  - pv-nfs.yaml
  - pvc.yaml
  - services/
  - ingress.yaml
  - ingress-admin.yaml
  
