apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-movies
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.20.10.2
    path: /volume1/media/movies
  mountOptions:
    - nfsvers=4.1
    - hard
    - nolock
    - async
    - noacl
    - nocto
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-tv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.20.10.2
    path: /volume1/media/tv
  mountOptions:
    - nfsvers=4.1
    - hard
    - nolock
    - async
    - noacl
    - nocto
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-music
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.20.10.2
    path: /volume1/media/music
  mountOptions:
    - nfsvers=4.1
    - hard
    - nolock
    - async
    - noacl
    - nocto
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.20.10.2
    path: /volume1/downloads
  mountOptions:
    - nfsvers=4.1
    - hard
    - nolock
    - async
    - noacl
    - nocto
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-movies
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-movies
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-tv
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-tv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-music
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-music
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-downloads
  resources:
    requests:
      storage: 1Ti
