context: pmdevers-MyHomeLab
contexts:
    pmdevers-MyHomeLab:
        endpoints:
            - https://pmdevers.na-west-1.omni.siderolabs.io
        auth:
            siderov1:
                identity: pmdevers@gmail.com
        cluster: MyHomeLab
