apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitopsdemo
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: gitopsdemo
  path: ./deploy/production
  prune: true
  wait: true
  timeout: 5m0s
  images:
  - name: ghcr.io/pmdevers/gitopsdemo
    newName: ghcr.io/pmdevers/gitopsdemo # {"$imagepolicy": "flux-system:gitopsdemo:name"}
    newTag: v1.0.0 # {"$imagepolicy": "flux-system:gitopsdemo:tag"}