apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "1.15.x"
  values:
    crds:
      enabled: true
  targetNamespace: cert-manager
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
