apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
- target:
    kind: IPAddressPool
  path: patches/metallb.yaml
- target:
    kind: L2Advertisement
  path: patches/metallb.yaml