apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: oauth2-proxy-secrets
    namespace: oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: oauth2-proxy/google/client-id
    - secretKey: client-secret
      remoteRef:
        key: oauth2-proxy/google/client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: oauth2-proxy/cookie-secret