apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sources
- cert-manager
#- oauth2-proxy
- nfs-provisioner
- external-secrets
#- onepassword-connect
- cilium
- intel-gpu
- s3-csi-driver