apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kafka-adventure-buildnr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kafka-adventure
  filterTags:
    pattern: ^main-[a-fA-F0-9]+-(?P<ts>.*)
    extract: $ts
  policy:
    numerical:
      order: asc
