apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            - name: GENERIC_TIMEZONE
              value: "Europe/Amsterdam"
            - name: NODE_ENV
              value: "production"
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: N8N_CORS_ALLOW_ORIGIN
              value: https://n8n.patrick-evers.nl
            - name: N8N_CORS_ALLOW_CREDENTIALS
              value: "true"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
