apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: patrick-evers
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: patrick-evers
  path: ./deploy/production
  prune: true
  wait: true
  timeout: 5m0s
  images:
    - name: ghcr.io/pmdevers/patrick-evers
      newName: ghcr.io/pmdevers/gitopsdemo # {"$imagepolicy": "flux-system:gitopsdemo:name"}
      newTag: v5.0.0 # {"$imagepolicy": "flux-system:gitopsdemo:tag"}
