apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: patrick-evers
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: patrick-evers
  path: ./deploy/production
  prune: true
  wait: true
  timeout: 5m0s
  images:
    - name: ghcr.io/pmdevers/patrick-evers
      newName: ghcr.io/pmdevers/patrick-evers # {"$imagepolicy": "flux-system:patrick-evers:name"}
      newTag: main-a42569b-1739285166 # {"$imagepolicy": "flux-system:patrick-evers:tag"}
