apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: food-truck
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: food-truck
  path: ./deploy/production
  prune: true
  wait: true
  timeout: 5m0s
  images:
    - name: ghcr.io/pmdevers/food-truck
      newName: ghcr.io/pmdevers/food-truck # {"$imagepolicy": "flux-system:food-truck:name"}
      newTag: main-d1a5623-1775483025 # {"$imagepolicy": "flux-system:food-truck:tag"}
