apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
    - name: configuration
  path: ./applications/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system