apiVersion: source.toolkit.fluxcd.io/v1 
kind: GitRepository 
metadata: 
  name: patrick-evers
  namespace: flux-system 
spec: 
  interval: 1m0s 
  ref: 
    branch: main 
  secretRef: 
    name: flux-system 
  url: https://github.com/pmdevers/patrick-evers.nl  