router bgp 65100
    ! Router ID
    bgp router-id 172.20.10.1
 
    ! Require explicit policy for eBGP neighbors
    bgp ebgp-requires-policy
 
    ! Relax autonomous system path matching for multipath routing
    bgp bestpath as-path multipath-relax
    maximum-paths 3
    
    ! Create peer-group HOMELAB with remote ASN 65200
    neighbor HOMELAB peer-group
    neighbor HOMELAB remote-as 65200
    neighbor HOMELAB password hunter2

    ! Add controller node IPs as neighbors
    neighbor 172.20.10.11 peer-group HOMELAB
    neighbor 172.20.10.12 peer-group HOMELAB
    neighbor 172.20.10.13 peer-group HOMELAB

    ! Apply Policies
    address-family ipv4 unicast
        redistribute connected
        neighbor HOMELAB activate
        neighbor HOMELAB next-hop-self
        neighbor HOMELAB soft-reconfiguration inbound
        neighbor HOMELAB route-map RM-HOMELAB-IN in
        neighbor HOMELAB route-map RM-HOMELAB-OUT out
    exit-address-family
exit

! VIPs within the service IP pool
ip prefix-list HOMELAB-IN seq 10 permit 172.20.10.0/24 le 32

! Accept Service IPs from cluster peers
route-map RM-HOMELAB-IN permit 10
    match ip address prefix-list HOMELAB-IN
exit

! Router client network
ip prefix-list HOMELAB-OUT seq 10 permit 172.20.10.0/24

! Broadcast client network for cluster peers
route-map RM-HOMELAB-OUT permit 10
    match ip address prefix-list HOMELAB-OUT
exit