apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
        app.kubernetes.io/part-of: jellyfin
    spec:
      containers:
      - name: bazarr
        image: lscr.io/linuxserver/bazarr:latest
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        - name: BAZARR_BASE_URL
          value: "/bazarr"
        ports:
        - containerPort: 6767
          name: http
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: bazarr
        - name: movies
          mountPath: /movies
        - name: tv
          mountPath: /tv
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nfs-config
      - name: movies
        persistentVolumeClaim:
          claimName: nfs-movies
      - name: tv
        persistentVolumeClaim:
          claimName: nfs-tv
