apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        app.kubernetes.io/part-of: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:10.11.3
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        - name: JELLYFIN_PublishedServerUrl
          value: "https://jellyfin.patrick-evers.nl"
        ports:
        - containerPort: 8096
          name: http
        resources:
          requests:
            cpu: 1000m
            memory: 3Gi
            gpu.intel.com/i915: 1
          limits:
            cpu: 4000m
            memory: 6Gi
            gpu.intel.com/i915: 1
        volumeMounts:
        - name: config
          mountPath: /config/config
          subPath: jellyfin/config
        - name: config
          mountPath: /config/metadata
          subPath: jellyfin/metadata
        - name: config
          mountPath: /config/plugins
          subPath: jellyfin/plugins
        - name: config
          mountPath: /config/log
          subPath: jellyfin/log
        - name: data
          mountPath: /config/data
        - name: cache
          mountPath: /cache
        - name: movies
          mountPath: /movies
        - name: tv
          mountPath: /tv
        - name: music
          mountPath: /music
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nfs-config
      - name: data
        emptyDir:
          sizeLimit: 10Gi
      - name: cache
        emptyDir:
          sizeLimit: 50Gi
      - name: movies
        persistentVolumeClaim:
          claimName: nfs-movies
      - name: tv
        persistentVolumeClaim:
          claimName: nfs-tv
      - name: music
        persistentVolumeClaim:
          claimName: nfs-music
