apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
        app.kubernetes.io/part-of: jellyfin
    spec:
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        - name: WEBUI_PORT
          value: "8082"
        - name: WEBUI_URL_BASE
          value: "/qbittorrent"
        ports:
        - containerPort: 8082
          name: webui
        - containerPort: 6881
          name: tcp-port
          protocol: TCP
        - containerPort: 6881
          name: udp-port
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-downloads
