apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
        app.kubernetes.io/part-of: jellyfin
    spec:
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        - name: HOST_WHITELIST
          value: "*"
        - name: API_WHITELIST
          value: "0.0.0.0/0,::/0"
        - name: URL_BASE
          value: "/sabnzbd"
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sabnzbd-config
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-downloads
