apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        app.kubernetes.io/part-of: jellyfin
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Amsterdam"
        - name: SONARR_BASE_URL
          value: "/sonarr"
        ports:
        - containerPort: 8989
          name: http
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: sonarr
        - name: tv
          mountPath: /tv
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nfs-config
      - name: tv
        persistentVolumeClaim:
          claimName: nfs-tv
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-downloads
