name: Flux Auto-PR
on:
  push:
    branches:
      - flux-image-updates

permissions:
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout

    - name: Check if there are any changes
      id: verify_diff
      run: |
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
        
    - name: Check if PR exists
      id: check-pr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        prs=$(gh pr list \
          --repo "$GITHUB_REPOSITORY" \
          --head "flux-image-updates" \
          --base "main" \
          --json title \
          --jq 'length')
        if (( prs > 0 )); then
          echo "skip=true" >> "$GITHUB_OUTPUT"
        fi
    - name: pull-request
      if: steps.verify_diff.outputs.changed == 'true' && steps.check-pr.outputs.skip != 'true'
      run: |
        gh pr create --title "Pulling ${{ github.ref }} into main" --body ":crown: *An automated PR*"