apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
      interval: 5m
  releaseName: onepassword-connect
  values:
    connect:
      create: true
      replicas: 2
  valuesFrom:
    - kind: Secret
      name: op-credentials
      valuesKey: connect.credentials
      targetPath: connect.credentials